# Generated by Django 4.2.3 on 2023-07-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20230710_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='session_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
